Blow up if we can't find a digest or anything fails.

diff --git a/modules/deploy/update-version b/modules/deploy/update-version
--- a/modules/deploy/update-version
+++ b/modules/deploy/update-version
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e
+
 # Whitespace-separated list of components of the form 'service|image|tag'.
 COMPONENTS="\
     flow-manager|gpii/universal|latest \
@@ -11,6 +13,7 @@ for component in $COMPONENTS ; do
     service=$(echo "$component" | awk -F'|' '{print $1}')
     image=$(echo "$component" | awk -F'|' '{print $2}')
     tag=$(echo "$component" | awk -F'|' '{print $3}')
+    echo "Looking up '$image:$tag' for service '$service'..."
     api_token=$(\
         curl -L -s \
         "https://auth.docker.io/token?service=registry.docker.io&scope=repository:$image:pull" \
@@ -21,21 +24,34 @@ for component in $COMPONENTS ; do
     #
     # The 'tr' is because curl outputs headers using network line endings (\r\n)
     # and our tools expect only \n.
-    digest=$(\
+    api_out=$(\
         curl -L -s \
         --head \
         -H "Authorization: Bearer $api_token" \
         -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
         https://index.docker.io/v2/$image/manifests/$tag \
+    )
+    digest=$(\
+        echo "$api_out" \
         | grep 'Docker-Content-Digest' \
         | awk '{print $2}' \
         | tr -d '\r' \
     )
+    if [ -z "$digest" ] ; then
+        echo "Could not calculate digest for $image:$tag. Aborting."
+        echo "Here was the output from the API:"
+        echo "$api_out"
+        exit 1
+    else
+        echo "...found digest '$digest'."
+    fi
 
     yaml="$yaml\n$service: \"$image@$digest\""
 done
 
 # Manual YAML construction is silly, but it avoids pulling in a dependency on a yaml library.
-echo "# This file is generated by $0." > version.yml
-echo "---" >> version.yml
-echo "$yaml" | sort >> version.yml
+outfile="version.yml"
+echo "Success! Writing $outfile..."
+echo "# This file is generated by $0." > $outfile
+echo "---" >> $outfile
+echo "$yaml" | sort >> $outfile
