Some updates to try to support kitchen-terraform 3.1.0.
I never got this completely working (kitchen-terraform was only
executing the root module, rather than apply-all'ing to all the
modules).

This is as far as I got before ultimately deciding that
kitchen-terraform wasn't adding enough value given the number of hacks
it took to get it working with terragrunt *-all.

(The hard-coded /usr/local/bin/terraform as part of the workaround
for kitchen-terraform dropping driver:cli; it is not particularly
portable.)

diff --git a/dev/test/bin/terragrunt_wrapper_test b/dev/test/bin/terragrunt_wrapper_test
--- a/dev/test/bin/terragrunt_wrapper_test
+++ b/dev/test/bin/terragrunt_wrapper_test
@@ -13,6 +13,12 @@ fail () {
     exit 1
 }
 
+echo -n "--version -> version..."
+out=$($base_cmd --version)
+echo "$out" | grep -Eq -- "\bversion" && success || fail "$out"
+echo -n "..."
+! echo "$out" | grep -q -- "--version" && success || fail "$out"
+
 echo -n "-state + -destroy -> create skip_next_apply..."
 tmp_state_dir="terragrunt_wrapper_test.tmp"
 skip_next_apply_file="terragrunt_wrapper.skip_next_apply"
@@ -53,6 +59,10 @@ echo -n "show -> skipped..."
 out=$($base_cmd show)
 echo $out | grep -q "Skipping subcommand:" && success || fail "$out"
 
+echo -n "workspace -> skipped..."
+out=$($base_cmd workspace)
+echo $out | grep -q "Skipping subcommand:" && success || fail "$out"
+
 echo -n "common args..."
 out=$($base_cmd whatever)
 echo $out | grep -q " --terragrunt-non-interactive" && success || fail "$out"
@@ -78,6 +88,7 @@ out=$($base_cmd whatever -state=/path/to/some/state)
 echo -n "output -> ignore-dependency-errors..."
 out=$($base_cmd output)
 echo $out | grep -q -- "--terragrunt-ignore-dependency-errors" && success || fail "$out"
+
 echo -n "-json -> jq..."
 out=$($base_cmd whatever -json)
 echo $out | grep -q "jq" && success || fail "$out"
